name: tour-of-heroes-environment
summary: Deploys Tour of Heroes on ARM
description: Deploys an Azure Web App without a data store
runner: ARM
templatePath: azuredeploy.json

parametersparameters:
  - id: name
    name: name
    description: 'Name of the Web App'
    type: string
    required: true